// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDWCNDOxr5e2P_tlKlNnHXMJw6nXBPeJeY',
    appId: '1:305496774776:web:8d7d1b0f618e556fb2758d',
    messagingSenderId: '305496774776',
    projectId: 'steak-a-cheval',
    authDomain: 'steak-a-cheval.firebaseapp.com',
    storageBucket: 'steak-a-cheval.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAifO0896Hg_fpURyzy7vwc-O1WRAk5PNA',
    appId: '1:305496774776:android:34c4241244e5580bb2758d',
    messagingSenderId: '305496774776',
    projectId: 'steak-a-cheval',
    storageBucket: 'steak-a-cheval.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyALfXmDa_cAgXTzQ_pOMs-k4VrhtGrqBw8',
    appId: '1:305496774776:ios:d17d080f4c3bb408b2758d',
    messagingSenderId: '305496774776',
    projectId: 'steak-a-cheval',
    storageBucket: 'steak-a-cheval.appspot.com',
    iosClientId: '305496774776-l2f395khego809hus0gda3fi8sa11pnd.apps.googleusercontent.com',
    iosBundleId: 'com.example.steackACheval',
  );
}
